import { Metadata } from 'next';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Identity Directions - BrandForge',
  description: 'Explore curated brand identity directions generated by BrandForge. Discover archetypes, palettes, and typography for your industry.',
  alternates: {
    canonical: 'https://brandforge.alfo.online/identity-directions',
  },
};

const directions = [
  {
    id: 'tech-innovator',
    title: 'The Tech Innovator',
    archetype: 'The Creator',
    description: 'A clean, modern identity designed for SaaS and AI startups. Features deep blues, stark whites, and precise sans-serif typography to convey trust and forward-thinking innovation.',
    link: '/industries/tech-startup-names'
  },
  {
    id: 'eco-conscious',
    title: 'The Eco-Conscious',
    archetype: 'The Innocent',
    description: 'Earthy, grounded aesthetics perfect for sustainable brands and health/wellness products. Uses muted greens and organic serif fonts to evoke natural harmony.',
    link: '/industries/health-wellness-names'
  },
  {
    id: 'bold-disruptor',
    title: 'The Bold Disruptor',
    archetype: 'The Rebel',
    description: 'High-contrast, energetic branding built to stand out. Ideal for streetwear or unconventional tech. Uses vibrant neons against deep dark backgrounds.',
    link: '/archetypes/outlaw-brand-names'
  },
  {
    id: 'premium-luxury',
    title: 'The Premium Luxury',
    archetype: 'The Ruler',
    description: 'Sophisticated and authoritative. Perfect for high-end fashion or real estate. Features elegant serif typography, monochromatic palettes with gold accents, and a minimalist approach.',
    link: '/industries/fashion-brand-names'
  }
];

export default function IdentityDirectionsPage() {
  return (
    <>
      <Header />
      <main className="flex-1 bg-[#0a0a0c] text-white">
        <section className="relative w-full py-24 md:py-32 px-4 overflow-hidden border-b border-white/5">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-900/20 via-[#0a0a0c] to-[#0a0a0c] pointer-events-none" />
          <div className="container relative z-10 max-w-4xl mx-auto text-center space-y-8">
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-br from-white to-white/50">
              Generated Identity Directions
            </h1>
            <p className="text-xl md:text-2xl text-white/60 font-light leading-relaxed">
              Explore our curated library of high-end brand identities. Each direction is psychologically engineered for specific industries and archetypes.
            </p>
          </div>
        </section>

        <section className="container max-w-5xl mx-auto px-4 py-16 md:py-24">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {directions.map((dir) => (
              <div key={dir.id} className="bg-white/5 border border-white/10 rounded-2xl p-8 hover:border-indigo-500/50 transition-colors">
                <div className="inline-block px-3 py-1 mb-4 text-xs font-semibold tracking-wider text-indigo-300 uppercase bg-indigo-500/20 rounded-full">
                  {dir.archetype}
                </div>
                <h2 className="text-2xl font-bold mb-4">{dir.title}</h2>
                <p className="text-white/70 mb-6 leading-relaxed">
                  {dir.description}
                </p>
                <Link href={dir.link} className="inline-flex items-center text-sm font-medium text-indigo-400 hover:text-indigo-300 transition-colors">
                  Explore this direction &rarr;
                </Link>
              </div>
            ))}
          </div>

          <div className="mt-16 text-center">
            <h3 className="text-2xl font-bold mb-4">Want to create your own?</h3>
            <p className="text-white/60 mb-8 max-w-2xl mx-auto">
              Use the BrandForge Generator Studio to map your industry and vibe to a coherent Brand DNA instantly.
            </p>
            <Link href="/" className="inline-block px-8 py-4 bg-indigo-600 hover:bg-indigo-700 text-white rounded-full font-semibold transition-colors">
              Open Generator Studio
            </Link>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
